name: hope_audio_slider
description: "A new Flutter package project."
version: 0.0.1-dev.1 # Marking as pre-release due to dependency on a pre-release package
homepage: https://github.com/todoyalee/home_audio_slider_package # Replace with your actual repository URL

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.7.2
  just_audio: ^0.10.2
  just_audio_background: ^0.0.1-beta.14
  rxdart: ^0.28.0
  cached_network_image: ^3.4.1
  audio_video_progress_bar: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  # If you have assets, specify them here
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # If you have custom fonts, specify them here
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
